server:
  port: 8080
jpa:
  database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  show-sql: true
  hibernate:
    ddl-auto: create
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user
    username: root
